### ISSUE TITLE
Add support for create trigger statements in mysql/mariadb migrations

### ISSUE THREAD

**Issue by stevepartridge** [Boostport/migration#24]
Additional support for triggers within MySQL/MariaDB statements.  Since triggers have a statement enclosed in the syntax which can contain a `;` it breaks the normal [parsing](https://github.com/Boostport/migration/blob/master/driver/mysql/mysql.go#L71-L72) of the migration.  

Using a common double semi-colon `;;` that is a result of various sql dump methods a basic approach could be something like the following before [driver/mysql.go:L71](https://github.com/Boostport/migration/blob/master/driver/mysql/mysql.go#L71-L72) :

```
import(
  ...
  "regexp"
  ...
)
...
if strings.Contains(content, "END;;") {

    triggerRegexp := regexp.MustCompile(`(?sm)^CREATE\sTRIGGER.*?END\;\;`)

    triggerStmts := triggerRegexp.FindAllString(content, -1)

    for i, _ := range triggerStmts {

      if _, err := driver.db.Exec(triggerStmts[i]); err != nil {
        return fmt.Errorf("Error executing statement: %s\n%s", err, triggerStmts[i])
      }

      // Remove the trigger statement from the migration content
      content = strings.Replace(content, triggerStmts[i], "", -1)
  }
}
```

Basic trigger example:

```
CREATE TRIGGER some_delightful_trigger
BEFORE UPDATE 
ON `some_magical_table` FOR EACH ROW
BEGIN
    INSERT INTO `some_magical_table_history` SET 
    `some_magical_table_id` = OLD.id,
    `a_column` = OLD.a_column;
END;;
```

**Comment by F21** [comment]
I just did some experiments with dumping a trigger using mysqldump and navicat.

For mysqldump, the format looks like this:

```sql
DELIMITER ;;
/*!50003 CREATE*/ /*!50017 DEFINER=`root`@`%`*/ /*!50003 TRIGGER before_employee_update 
    BEFORE UPDATE ON employees
    FOR EACH ROW 
BEGIN
    INSERT INTO employees_audit
    SET action = 'update',
     employeeNumber = OLD.employeeNumber,
        lastname = OLD.lastname,
        changedat = NOW(); 
END */;;
DELIMITER ;
```

For Navicat:

```sql
DELIMITER ;;
CREATE TRIGGER `before_employee_update` BEFORE UPDATE ON `employees` FOR EACH ROW BEGIN
    INSERT INTO employees_audit
    SET action = 'update',
     employeeNumber = OLD.employeeNumber,
        lastname = OLD.lastname,
        changedat = NOW(); 
END
;;
```

I think the best way to would be search for the `DELIMITER` keyword to get the delimiter, then ignore all `;` until after seeing the delimiter.

**Comment by stevepartridge** [comment]
Totally, that'd great.

**Comment by F21** [comment]
After some investigation, I think parsing for the `DELIMITER` keyword will be very complex (if not very error-prone), unless someone wants to port the parsing logic for the `DELIMITER` keyword from the official MySQL client.

Initially, I thought it would be possible to naively use `(?i)^delimiter(.+)` to split the SQL, however, the following are all valid:

- `CREATE TABLE test_table1 (id integer not null primary key);DELIMITER;;`

- `CREATE TABLE test_table1 (id integer not null primary key);DELIMITER;;CREATE TABLE test_table2 (id integer not null primary key);;`

- `DELIMITER;;`

- `DELIMITER abc`

These cases are pretty much impossible to achieve using regex. Another option is to define our own delimiter for the library, similar to goose or sql-migrate.

For example:

```sql
-- migrate
CREATE TABLE test_table1 (id integer not null primary key);

-- migrate
CREATE TABLE test_table2 (id integer not null primary key);

-- migrate
/*!50003 CREATE*/ /*!50017 DEFINER=`root`@`%`*/ /*!50003 TRIGGER test_trigger_1
		BEFORE UPDATE ON test_table1
		FOR EACH ROW
BEGIN
		INSERT INTO test_table2
		SET id = OLD.id;
END */

-- migrate
CREATE TRIGGER`test_trigger_2`BEFORE UPDATE ON`test_table1`FOR EACH ROW BEGIN
		INSERT INTO test_table2
		SET id = OLD.id;
END
```

**Comment by stevepartridge** [comment]
That was my concern as well.  That's why I proposed something basic, but was by no means solid.  The custom delimiter would work without complicating things.  Could even have `;` be the default and allow for an override/custom option as part of the Driver struct.  That way it could be leveraged on a case by case basis.

**Comment by F21** [comment]
I spent some time thinking about this and I think relying on `;;` might not be very apparent if someone is skimming through the `.sql` file. In addition, we would also have to account for the case for creating stored procedures.

I think using `-- migration StatementEnd` and `--migration StatementBegin` would explicitly call out delineation between statements where required. This also means that it's also possible to introduce a `--migration NoTransaction` comment which can be used to signal that the migration should not be run as a transaction and revert #25. The benefit of this is that it is explicit and apparent why we need to run a certain migration without transactions.

**Comment by F21** [comment]
You can now use SQL comments to delineate your statements.

See the examples here: https://github.com/Boostport/migration#writing-migrations
