### ISSUE TITLE
Issue using Postgres Migration Driver

### ISSUE THREAD

**Issue by felixcolaci** [Boostport/migration#44]
Hi,

I have tried to implement a db migration setup with this package - without success to this point.

I experimented a bit and for my setup it seems like the Driver Implementations in the ./driver package don't implement the Driver interface.
![missinginterfaceimplementation](https://user-images.githubusercontent.com/34742348/45928652-7ddcb680-bf47-11e8-8dbd-cae84dd219c2.PNG)

My code doesn't recognize the driver instance I created using the `postgres.NewFromDB()` method as a valid implementation of the driver interface.

When I open your code directly the driver implementations aren't recognized as valid implementations of the driver interface either. Whereas the mockDriver you implemented in the package root is recognized correctly.

![driver](https://user-images.githubusercontent.com/34742348/45928670-ca27f680-bf47-11e8-9257-bfbe77cc9b20.PNG)

I experimented a little bit and it seems like if I modify the driver interface slightly to explicitly import the package itself for the PlannedMigration parameter of the Migrate() method all interface implementations are recognized correctly.

![importhack](https://user-images.githubusercontent.com/34742348/45928713-8681bc80-bf48-11e8-90a7-755096d7c90d.PNG)

To me this seems like a strange behaviour since there shouldn't be an issue with the original interface declaration and implementations as they are.
So the question is wether my setup is just misbehaving or if you want to adapt this change. Unfortunately this breakes the mockDriver implementation. So one would have to find a solution for that.

I still think that Intellij is getting something wrong. Please let me know if you have any advice on how to use this lib properly.

Kind regards,
Felix

**Comment by F21** [comment]
Hey @felixcolaci, which version of Goland are you using? I am using 2018.2.3 with go modules enabled for the project. I am currently trying to set up a test project to reproduce, but one of the transitive dependencies appear to be broken:

```
go get -u github.com/Boostport/migration
go: finding golang.org/x/net latest
go: finding github.com/jcmturner/gofork latest
go: finding golang.org/x/sync latest
go: finding github.com/gobuffalo/shoulders latest
go: finding github.com/gobuffalo/genny latest
go: finding github.com/gobuffalo/flect latest
go: finding golang.org/x/crypto latest
go: finding github.com/serenize/snaker latest
go: finding github.com/gobuffalo/licenser latest
go: finding github.com/markbates/oncer latest
go: finding gopkg.in/tomb.v1 latest
go: finding gopkg.in/check.v1 latest
go: finding github.com/shurcooL/go-goon latest
go: finding golang.org/x/sys latest
go: finding github.com/shurcooL/highlight_go latest
go: finding github.com/sourcegraph/annotate latest
go: finding github.com/shurcooL/highlight_diff latest
go: finding github.com/shurcooL/octicon latest
go: finding github.com/sourcegraph/syntaxhighlight latest
go: finding github.com/shurcooL/go latest
go: finding github.com/shurcooL/sanitized_anchor_name latest
go: gopkg.in/russross/blackfriday.v1@v1.5.2: go.mod has non-....v1 module path "github.com/russross/blackfriday" at revision v1.5.2
go: finding golang.org/x/tools latest
go get: error loading module requirements
```

**Comment by F21** [comment]
Hey @felixcolaci 

I was able to set up a test project properly in Goland.

I created a new Go modules project in Goland and did the following:
1. `go init github.com/f21/myproject`
2. `go get  github.com/Boostport/migration`
3. Create `main.go` in the root of the project.
4. Added the following to `main.go`:
```go
package main

import (
	"fmt"
	"github.com/Boostport/migration"
	"github.com/Boostport/migration/driver/postgres"
	"github.com/gobuffalo/packr"
)

func main(){
	packrSource := &migration.PackrMigrationSource{
		Box: packr.NewBox("migrations"),
	}

	driver,_ := postgres.New("asdf")

	applied, err := migration.Migrate(driver, packrSource, migration.Up, 0)

	fmt.Println(applied, err)
}
```

I do not have any errors in my IDE and the code also compiles correctly using `go build`.

Is it possible that your IDE is getting confused with what's in your GOPATH? For example, if you had a copy of `migration` in `GOPATH/src/...` and another copy under `GOPATH/pkg/mod`?

**Comment by felixcolaci** [comment]
Thank you so much for looking into this. I feel a little bit stupid right now but adding github.com/gobuffalo/packr to my go.mod file and running `go mod download` did the trick...

I think this issue is resolved :)

**Comment by F21** [comment]
Glad you got it working!
