### ISSUE TITLE
Include code-quality checks

### ISSUE THREAD

**Issue by lopezator** [Boostport/migration#47]
Including code-quality checks should be a must for every go project.

We tend to use in our projects the following ones: [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports), [golint](https://github.com/golang/lint), [vet](https://golang.org/cmd/vet/), [megacheck](https://github.com/dominikh/go-tools/tree/master/cmd/megacheck), [errcheck](https://github.com/kisielk/errcheck). 

They han proven to be very useful.

Possibly add more?

I was thinking of adding a Makefile, refactor the code to pass all the checks, and possibly integrate that Makefile check as a Travis CI building stage?

I would take over this.

Thoughts?

**Comment by F21** [comment]
Hey @lopezator, thanks for offering to work on this. I think this is an excellent idea and certainly look forward to your contribution.

Do we need to use a makefile? Would running the checks using a shell script suffice?

**Comment by F21** [comment]
That makes sense. Let's go with makefiles then.

**Comment by F21** [comment]
Merged in #49
