### ISSUE TITLE
Cannot use golang driver along with a database driver

### ISSUE THREAD

**Issue by lopezator** [Boostport/migration#50]
It seems that Golang migrations doesn't integrate well with other `regular database` migrations.

To reproduce the issue I'm facing, imagine an scenario where I have a `migrations` folder with a single sql migration:

* 1_step1.up.sql
* 1_step1.down.sql

I've migrated this `up` using `db`, so I have one row `1_step1` contents in the `schema_migration` table.

Then I want to build a `go` migration as a second step like this:

```
src := golang.NewSource()
src.AddMigration("2_step2", migration.Up, func() error {
    fmt.Println("I'm migrating up")
}
src.AddMigration("2_step2", migration.Down, func() error {
    fmt.Println("I'm migrating down")
}
```

I've used the postgres driver to return the contents of the `schema_migration` table like this:

```
drv, err := postgres.New(dbURL)
if err != nil {
	return err
}
applied := func() ([]string, error) {
	return drv.Versions()
}
```

`drv.Versions() `  returning only 1 on this point, `1_step1` which is fine.

If I try to migrate the `go` `2_step2` over the first `db` `step_1` however it doesn't apply anything.

* `getMigrations()` returns only the `go` source manually added files `2_step2` in this case.
* `appliedMigrations` has only `db` entries `1_step1`.
* `migrationsToApply` is empty, so the `go` migration `2_step2` migration never gets applied.

Something I misunderstood or doing wrong?

Btw I have some improvements in mind for the docs, took me a while to understand some points.

CC\ @F21

**Comment by F21** [comment]
It's not possible to perform and mix migrations over multiple sources. In general, most migration libraries (written in Go) also performs migrations within 1 source.

- The `getMigrations()` function only returns migrations for the current driver and not all migrations.
- `appliedMigrations` should only contain applied migrations for the current driver.
- `migrationsToApply` depends on the current driver and source being used.

Can you post an example in a `main()` function that is easily runnable to show what you are trying to achieve?

**Comment by lopezator** [comment]
Maybe what I was trying to do doesn't make sense at all and I am using badly the tool.

I created a test repository to show you the idea I had:

https://github.com/lopezator/migration-sandbox

What I was expecting was:

1.- Migrate a first step using postgres driver
2.- Migrate a second step using golang driver
3.- Have two entries on the db `schema_migrations` table with the postgres migration and the golang migration.

**Comment by F21** [comment]
Thanks for creating the test repo, @lopezator ! What you're trying to do will not work, unfortunately. In general, I have only had use-cases where my migrations existed in 1 source and were only used with 1 driver.

In your situation, I think you can try either of the following:
- Used Golang for migrations and perform the postgres migration bits directly in Go code. The downside of this approach is that you will probably need to implement or copy the implementation for the Postgres driver into your code.
- Create a "super" source that wraps the Golang and Packr migration sources and create a "super" driver that wraps the Postgres and Golang drivers. I am not entirely sure if this is feasible as I didn't have time to try a test implementation, but if the interfaces you need to implement are here:
- https://github.com/Boostport/migration/blob/master/source.go#L12
- https://github.com/Boostport/migration/blob/master/driver.go#L4

**Comment by lopezator** [comment]
Thank for all the details @F21 ! :) You csan close the issue if you wish as the issue is in my end, anyway I will keep you updated in case you're curious.

**Comment by F21** [comment]
Thanks @lopezator! I will close this issue. Please do comment when you find a way to solve your problem :smile:

**Comment by lopezator** [comment]
I ended up creating my own migration library to accomplish this.

https://github.com/lopezator/migrator

Just wanted to say thank you as migration served as inspiration for it!
