### ISSUE TITLE
What is the purpose of tools.go?

### ISSUE THREAD

**Issue by kszafran** [Boostport/migration#69]
I have been wondering for quite some time why in our projects we end up with a lot of linter dependencies in go.mod. It seems they are included transitively through Boostport/migration. They seem to be imported in `tools.go`. What is it? Would it be possible to keep go.mod clean of linter dependencies?

**Comment by F21** [comment]
These are development tools used for development and for continuous integration. I don't think it's possible to remove them from `go.mod` as we use it to pin the correct version of those tools for reproducible builds. Unfortunately, Go does not have the concept of dev dependencies, so it won't be possible to remove them.

**Comment by kszafran** [comment]
We also use golangci-lint in our repositories and we don't need to add it to the code. Maybe I could help if I had a better understanding of how `tools.go` is used. For example, in `tests.yml` I see:
```
go install github.com/golangci/golangci-lint/cmd/golangci-lint
```
That could be pinned to a version:
```
go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.41.1
```

Similiarly, in docker-compose.yml:
```
go install github.com/unchartedsoftware/witch
...
go install github.com/go-bindata/go-bindata/v3/go-bindata
```
could be replaced with
```
go install github.com/unchartedsoftware/witch@0.2.10
...
go install github.com/go-bindata/go-bindata/v3/go-bindata@v3.1.3
```

I can make a PR if you agree with this approach.

**Comment by kszafran** [comment]
https://github.com/Boostport/migration/pull/70
